#!/bin/bash
# ru this script with one argument
# the goal is to find out if the argument is a file or a directory
if [ -f $1 ]
then
  echo "$1 is a file"
elif [ -d $1 ]
then
  echo "$1 is a directory"
else
  echo "I don't know what \$1 is"
fi
exit 0
